### ISSUE TITLE
Free and busy

### ISSUE THREAD

**Issue by drentsarchief** [niccokunzmann/open-web-calendar#135]
Hi,

In my calendar I have the option for free and busy. The .ics export file also contains these fields. I only do not see these fields in the calendar view. Is there a way to show these fields? So busy does not show any content information due to privacy reasons.

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/135">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/135/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/135/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, that sounds like a valuable view to have. Can you provide an ICS file as an example?
The library that does the free/busy would be python-recurring-ical-events, not this project. If that library implements it, the display of it can be implemented here. If you like, you can open an issue there, too. If not, I will. The ICS example is very important.

Also, I provide this free of charge under an open license because I believe in empowering people. I will focus on getting it served from somewhere else in the next week because Heroku shuts down free deployments. If you want and can - there are ways to support this project.

Thanks for reporting this. I really like that feature!

**Comment by drentsarchief** [comment]
Hi,
[agenda.zip](https://github.com/niccokunzmann/open-web-calendar/files/10039362/agenda.zip)
I have added a simple example of my .ICS. 
I use the field to make an appointment on e.g. the iphone. The field is called show if: I choose available or busy there. Actually, I would not like to see the appointment in the agenda, but a flat e.g. red = busy and green is available. In this way I can use the AVG for privacy information

**Comment by niccokunzmann** [comment]
Thanks for the example!

I can see this

```
SUMMARY:Geboekt
TRANSP:OPAQUE
```
and this
```
SUMMARY:Optie
TRANSP:TRANSPARENT
```

There is a difference to note: The open-web-calendar does request the clear ICS and so can the users. You cannot use it and prevent users from requesting the content themselves. It is hidden from their eyes maybe but there is a way to still look at it - if this makes sense. It is not secured.

**Comment by drentsarchief** [comment]
Thanks for the reply/

Is it possible to use these 2 fields and then e.g. color the day via CSS. So only show a color and not the content of the appointment. See my enclosed example
![example](https://user-images.githubusercontent.com/77052414/203588950-1a055744-14b6-496c-af73-ec8c05ab3e5b.jpg)

**Comment by niccokunzmann** [comment]
I think, this is possible. It is only a question of who would implement that. I am happy to assist and merge. I think, this is quite a nice feature. I can work on it and my priority is to get the open-web-calendar moved away from Heroku on my own server and then I would work on something I get paid for because I would like to feed the family.

To implement that, I see several ways to do it:
- We make this a feature in the web UI like a checkbox so you can say that a certain URL should be visible like you showed in the picture. - We can do this for all URLs or for one URL.
- We pass the event's field `TRANSP` to the requested JSON
- We add the `TRANSP` field from the JSON as a CSS class like `TRANSP-OPAQUE`
- We customize the CSS class
    - to have a color
    - to not view the content (this can be an extra checkbox because people might like to see the color and the text)
    - As this is a CSS class then, it can be customized to your desired colors below like the other colors of the calendar (extra step but really useful)

**Comment by drentsarchief** [comment]
Sounds good!
Can you send me a private email or message so we can discuss the details?

**Comment by niccokunzmann** [comment]
I will formulate an open proposal for my FOSS work later and send a link. What it looks like at the moment is that: If you are a single developer, I would like to receive your hourly wage. If you are a company, I take highest wage in the company per hour. This filters out proud companies which like inequality. In any case, I am happy to assist implementing it. 

I wonder what you think about that. It is not normal, true.

Sorry for the delay. I had to think and we are just recovering from illness.

**Comment by alesander2** [comment]
hi @niccokunzmann , i am taking over this project. have you worked out how to show free/busy with the open web calendar? whats the status?

**Comment by niccokunzmann** [comment]
Hi @alesander2,

I arrived here with my thoughts of how to possibly implement this:

- [ ] (important) create a flag false/true in the default_configuration.yml for whether to show it as free/busy
- [ ] (important) Add this to the index.html template to configure (default false)
- [ ] (important) Remove the text and set the CSS class for the event when the flag is not false
- [ ] (nice) choose the colors for the FREE/BUSY/TENTATIVE
- [ ] (nice) add translations for FREE/OPTIE/GEBOEKT

To note:
- You can get the categories FREE/BUSY/TENTATIVE directly from the VEVENT class
- You can add unit tests/web tests to make sure this is not destroyed
- The CSS class for styling the colors can be set like it happens when there is an error.
- My feeling is that testing is important here as we could have cases like two overlapping events. It might be worth exporting the free/busy part into another package that can be used with recurring-ical-events. Like: If you can write a python module with this interface:

```
class TagTheTimeSpans:
    def __init__(self): ...
    def tag_time(self, start, stop, tag="busy"):
        """Tag the time between start and stop with a tag."""
    def get_tagged_times_between(self, start, stop):
        """ => [{tags=[], start=start, stop=t1}, {tags=["busy"], start=t1, stop=t2}, {tags=[], start=t2, stop=stop}]
        """
    def add_free_busy_events(self, events= []):
        for event in events:
            self.tag_time(event["DTSTART"], event["DTEND"], tag=event["TRANSP"])
    def add_calendar(self, calendar, start, stop):
            self.add_free_busy_events(recurring_ical_events.of(calendar).between(start, stop))
```

The good thing about splitting this off is that it will be reused somewhere else and developers will fix the edge cases.


If you have any questions, you can ask me. I am helping maintain this and go forward. Also, if you want to go another way than what I have written, that is totally ok.

**Comment by niccokunzmann** [comment]
I opened an issue to approach this one in an easy way, for now: https://github.com/niccokunzmann/open-web-calendar/issues/305

**Comment by niccokunzmann** [comment]
Since #306, there are CSS classes available to color in. What do you think? How would you like to go on?

**Comment by niccokunzmann** [comment]
I created this example: https://open-web-calendar.quelltext.eu/templates/#free-and-busy

Have a look if this is what you are looking for.

**Comment by niccokunzmann** [comment]
Nice, I added the text "Free" and made all days without events actually green.

![grafik](https://github.com/niccokunzmann/open-web-calendar/assets/564768/39863780-dd0e-46af-b4e1-cb9a7e1276f9)

You can edit the example and add your own calendar link. I think, it should work. Please report back.

**Comment by niccokunzmann** [comment]
There is a calendar that can be modified in the examples that creates this view. I close this issue as completed. If you have any questions, or comments, please reach out!
