### ISSUE TITLE
Integrate into cloudron

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#143]
https://www.cloudron.io/ is a foss alternative to the easy hosting with heroku. It would be nice to

- [ ] add the metadata to easily host with cloudron
- [ ] get the project listed on the apps' page

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/143">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/143/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/143/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
@nebulade, since you packaged the app, would you be interested in auto-packaging the open-web-calendar from this repository? What would be required? I see a configuration file is required here: https://docs.cloudron.io/packaging/tutorial/

**Comment by nebulade** [comment]
To give a bit of context, I am one of the founders of Cloudron and packaged the app for a specific use-case I have. Since Cloudron packages are a bit platform specific and we add custom tests to ensure proper updates, we always create our own package repositories, from which we build and test updates before pushing them out to our users. Since updates often require manual intervention (maybe not for open web calendar, given the scope of the app), we don't use automated update pipelines from upstream release tags. In this case the package repo is at https://git.cloudron.io/cloudron/openwebcalendar-app . It still lacks tests, polish and some meta info, but once the package is published we will monitor the release updates from this repo and ensure the app is updated timely.

So I guess this issue can be closed once the package is published to our library.

Btw does open web calendar have some icon or logo which we can use?

**Comment by niccokunzmann** [comment]
@nebulade There is a logo now and it can be found here: https://github.com/niccokunzmann/open-web-calendar/tree/master/static/img/logo

**Comment by nebulade** [comment]
ah nice thanks, I am apparently blind :D its added now

**Comment by niccokunzmann** [comment]
I just now added a logo. Let me know if you need any more info or help for the integration.

**Comment by nebulade** [comment]
I've added OpenWebCalendar now as an unstable package to our app library https://forum.cloudron.io/topic/10670/open-web-calendar-is-now-available

Once we got some feedback, fixed initial issues and at least one upstream release further, we will mark it as stable then.

So this can be closed. Thanks!

**Comment by niccokunzmann** [comment]
@nebulade, thanks! I added links in the README and closed the issue. I also created a new release. I wonder how the new releases flow into Cloudron - I do not have to know ;) Merry Christmas!

**Comment by nebulade** [comment]
New package is published. We are tracking upstream project releases by the release tags and then start updating the package and do automated and/or some manual smoketesting.
