### ISSUE TITLE
Add timezone function 

### ISSUE THREAD

**Issue by mtihelpdesk** [niccokunzmann/open-web-calendar#171]
Calendar event dates are incorrectly displays due to UTC time on the busybox.

**Comment by niccokunzmann** [comment]
I like to see that, too and having time zones is almost implemented. The offset is due to the fixed time zone offset that is passed by the dhtmlx scheduler by default. If this is replaced with a known timezone, then all should go well. Javascript could add the browser time zone if given to as an additional argument taking precedence over the time offset. That would be a few lines of code. 2 in python, 2 in JS.

**Comment by niccokunzmann** [comment]
See also #154

**Comment by niccokunzmann** [comment]
I added this in v1.7 and it should be live tomorrow. You can fix your calendar to a timezone, too.
