### ISSUE TITLE
choose between month, week and day view

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#30]
I would like to specify the default view of the calendar: month, day or week.
- [ ] add parameter description on front page
- [ ] add dropdown for view on front page
- [ ] implement parameter reading of the specification in the configure.js file.

**Comment by firrm** [comment]
If someone else needs a quick fix in the file /templates/calendar/dhtmlx.html change
<body> to 
`<body onload="changeView()">`
and add
`  <script> function changeView(){ scheduler.setCurrentView(null,"week");}; </script`
before </body>

Instead of week, you can choose any of the view. Also from here it is straightforward to include this in the specification[] (ie. not hard-code it).

Will submit once I have more time, for now we just needed to get it running....

**Comment by niccokunzmann** [comment]
This seems to be implemented:

![image](https://user-images.githubusercontent.com/564768/214053564-094b5d39-1705-405f-9194-6a8386e07ebc.png)
